version: "3.9"

services:
  langflow:
    user: root
    image: langflowai/langflow:latest 
    pull_policy: always  
    ports:
      - "7860:7860"
    volumes:
      - data_volume_frontend:/app/data/langflow  # Langflow data in subdirectory
    depends_on:
      - qdrant
    environment:
      - LANGFLOW_DATABASE_URL=sqlite:///data/langflow/langflow.db # Updated path
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=aqyn
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}
    volumes:
      - data_volume_frontend:/qdrant/data  # Qdrant data in subdirectory

volumes:
  data_volume_frontend:  # Single named volume