version: "3.9"

services:
  langflow:
    image: langflow/langflow:latest
    ports:
      - "7860:7860"
    volumes:
      - langflow_data:/app/data
    depends_on:
      - qdrant
      - dagster-webserver
      - minio  # Minio dependency
    environment:
      - LANGFLOW_DATABASE_URL=sqlite:///data/langflow.db
      - QDRANT_URL=qdrant
      - QDRANT_PORT=6333
      # Minio configuration for Langflow (example)
      - LANGFLOW_S3_ENDPOINT=minio:9000
      - LANGFLOW_S3_ACCESS_KEY_ID=aqyn
      - LANGFLOW_S3_SECRET_ACCESS_KEY=aqyn
      - LANGFLOW_S3_BUCKET_NAME=aqyn-bucket # Example bucket name

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/data

  dagster-webserver:
    image: dagster/dagster:latest
    ports:
      - "3000:3000"
    volumes:
      - ./dagster_home:/opt/dagster/dagster_home
      - ./dags:/opt/dagster/dags
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
      - DAGSTER_DATABASE_URL=sqlite:///data/dagster.db

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # Minio web UI and API
      - "9001:9001" # Minio console (optional)
    environment:
      MINIO_ACCESS_KEY: aqyn  # Access key
      MINIO_SECRET_KEY: aqyn  # Secret key
    volumes:
      - minio_data:/data # Persist Minio data

volumes:
  langflow_data:
  qdrant_data:
  dagster_home:
  minio_data: # Minio data volume