version: "3.9"

services:
  dagster-webserver:
    build:
      context: .
      dockerfile: ./dag/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PYTHONPATH=/opt/dagster/app
      - QDRANT_HOST=rag.aqyn.tech
      - QDRANT_PORT=6333
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_COLLECTION=aqyn
      - DAGSTER_HOME=/opt/dagster/dagster_home
      - OPENAI_API_KEY=${OPENAI_API_KEY} 
    volumes:
      - dagster_home1:/opt/dagster/dagster_home
      - ./dag/dagster.yaml:/opt/dagster/dagster.yaml
      - ./data:/opt/dagster/data
    command: ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000", "-w", "/opt/dagster/app/workspace.yaml"]

  dagster-daemon:
    build:
      context: .
      dockerfile: ./dag/Dockerfile
    environment:
      - QDRANT_HOST=rag.aqyn.tech
      - QDRANT_PORT=6333
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_COLLECTION=aqyn
      - DAGSTER_HOME=/opt/dagster/dagster_home
      - OPENAI_API_KEY=${OPENAI_API_KEY} 
    depends_on:
      - dagster-webserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - dagster_home1:/opt/dagster/dagster_home
      - ./data:/opt/dagster/data
    command: ["dagster-daemon", "run"]

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=aqyn
      - MINIO_ROOT_PASSWORD=aqynpassword
    command: server /data/minio --console-address ":9001"
    volumes:
      - data_volume:/data/minio

volumes:
  data_volume:
  dagster_home1: