version: "3.9"

services:
  langflow:
    image: langflow/langflow:latest
    ports:
      - "7860:7860"
    volumes:
      - data_volume:/app/data/langflow  # Langflow data in subdirectory
    depends_on:
      - qdrant
      - dagster-webserver
      - minio
    environment:
      - LANGFLOW_DATABASE_URL=sqlite:///data/langflow/langflow.db # Updated path
      - QDRANT_URL=qdrant
      - QDRANT_PORT=6333
      - LANGFLOW_S3_ENDPOINT=minio:9000
      - LANGFLOW_S3_ACCESS_KEY_ID=aqyn
      - LANGFLOW_S3_SECRET_ACCESS_KEY=aqyn
      - LANGFLOW_S3_BUCKET_NAME=aqyn-bucket

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - data_volume:/qdrant/data  # Qdrant data in subdirectory

  dagster-webserver:
    image: dagster/dagster:latest
    ports:
      - "3000:3000"
    volumes:
      - data_volume:/opt/dagster/dagster_home # Dagster home in subdirectory
      - ./dags:/opt/dagster/dags
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
      - DAGSTER_DATABASE_URL=sqlite:///data/dagster/dagster.db # Updated path

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: aqyn
      MINIO_SECRET_KEY: aqyn
    volumes:
      - data_volume:/data/minio  # Minio data in subdirectory

volumes:
  data_volume:  # Single named volume