{{- if .Values.minio.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aqyn.fullname" . }}-minio-data-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aqyn.minio.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.minio.persistence.accessMode }}
  {{- if .Values.minio.persistence.storageClass }}
  storageClassName: {{ .Values.minio.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
{{- end }}

---
{{- if .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aqyn.fullname" . }}-postgres-data-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aqyn.postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.postgres.persistence.accessMode }}
  {{- if .Values.postgres.persistence.storageClass }}
  storageClassName: {{ .Values.postgres.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
{{- end }}